### ISSUE TITLE
cant open jar file

### ISSUE THREAD

**Issue by mrlexiaunt** [RANKTW/Discord-Token-Checker#17]
![image](https://user-images.githubusercontent.com/85587979/146654284-566c1844-3ca2-4854-b706-7866fea1f826.png)

any idea how to fix?

**Comment by mrlexiaunt** [comment]
i cant open it, i installed java and nothing :/

**Comment by RANKTW** [comment]
what Java version you installed
please make sure it's 1.8 and is download from http://java.com
you can type `java -version` in command prompt to check what version you currently using

**Comment by mrlexiaunt** [comment]
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

**Comment by RANKTW** [comment]
yeah wrong version
you need to uninstall the other version 
and download from http://java.com only

**Comment by mrlexiaunt** [comment]
okey thanks, and last why it use like 5gb of ram? 
![image](https://user-images.githubusercontent.com/85587979/147370954-8881db42-78ea-49d8-89cc-d78c499a8f81.png)

**Comment by RANKTW** [comment]
did you try to use the Login Discord functions?
if so that is probably why

**Comment by mrlexiaunt** [comment]
yep yep, but why it consume that munch ram?

**Comment by RANKTW** [comment]
because it simulates a browser
