### ISSUE TITLE
Browser no longer open

### ISSUE THREAD

**Issue by BrokedTV** [RANKTW/Discord-Token-Checker#22]
It was working fine but now, when i log in one token, the client runs into error and won't open.

**Comment by BrokedTV** [comment]
Well, this is awkward
looks like discord has crashed unexpectedly
we've tracked the error and will get tight on it.

**Comment by BrokedTV** [comment]
Any chance to get an update or make this open source again so we can help out with keeping it updated? it's a really usefull tool!

**Comment by HjInYoMaMa** [comment]
Make your own,  easy solution.

**Comment by BrokedTV** [comment]
> Make your own, easy solution.

nice useless comments
