### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by nusdy** [RANKTW/Discord-Token-Checker#29]
Hello. excuse my ignorance. I have MAC I can not install the program. Are there some steps to follow to be able to do it or is this only on windows?
Thnks!!!!!

**Comment by RANKTW** [comment]
Install Java 8 - http://java.com/download

**Comment by nusdy** [comment]
I have installed it. And when I open the DTC file nothing happens. Does an app supposedly have to be opened?
Thanks for the help

<img width="628" alt="Captura de pantalla 2022-03-29 a las 17 26 03" src="https://user-images.githubusercontent.com/102556334/160647675-73b3c655-f603-45f7-b034-549d095d26cc.png">

**Comment by nusdy** [comment]
Will it be for my computer?

<img width="346" alt="Captura de pantalla 2022-03-29 a las 17 27 21" src="https://user-images.githubusercontent.com/102556334/160648015-f16a960a-8292-466c-be81-9e0a56639f27.png">
ill it be for my computer?

**Comment by RANKTW** [comment]
type `java -version` in the command prompt
and send the screenshot here

**Comment by nusdy** [comment]
![Captura de pantalla 2022-03-30 a las 4 27 06](https://user-images.githubusercontent.com/102556334/160739092-247a5fbf-0657-4cb9-8cd1-df474be3585c.png)

**Comment by RANKTW** [comment]
wrong version.
uninstall it then download from http://java.com/download again

**Comment by nusdy** [comment]
I don't know what's going on but I have the latest version of Java installed

<img width="373" alt="Captura de pantalla 2022-03-30 a las 5 33 14" src="https://user-images.githubusercontent.com/102556334/160746114-7fa2c03b-e694-4190-9385-43dffc977a78.png">

**Comment by nusdy** [comment]
<img width="351" alt="Captura de pantalla 2022-03-30 a las 5 27 11" src="https://user-images.githubusercontent.com/102556334/160746143-3d80295a-5048-478e-b371-a214bc4a910d.png">

**Comment by RANKTW** [comment]
you have installed multiple versions, you need to uninstall other outdated version

**Comment by nusdy** [comment]
I don't know how to do it, forgive my stupidity. I did when I opened java and selected delete. Apparently he hasn't

**Comment by RANKTW** [comment]
I'm not a Mac user so I don't know either 
but try google it you should be able to find a lot answers

**Comment by nusdy** [comment]
ok thanks for all friends
