### ISSUE TITLE
I bought your token for 25$ ltc and only 50 worked

### ISSUE THREAD

**Issue by zzze6995** [RANKTW/Discord-Token-Checker#40]
I bought your token for 25$ ltc and only 50 worked
i bought 531 tokens after using dmego
most of the tokens saying captcha detected and than after rechecking the tokens all of them dont work 
only 50 working left

**Comment by zzze6995** [comment]
dm zzze#6995 i want a support since i cant contact on telegram

**Comment by RANKTW** [comment]
dmego is being activity getting patched everyone knows that
and NO we will not use discord to contact you. There have many impersonators out there don't just leave your discord public like that 
if you can't use telegram then use website live chat or email here is not the place
