### ISSUE TITLE
I want to know something

### ISSUE THREAD

**Issue by MRX0077** [RANKTW/Discord-Token-Checker#43]
Hey guys  your program was unable to check the new format of tokens (more characters and start with is M), but after that you updated it to be able to check the new format tokens, so I need to know if you changed it. What makes it compatible with the new tokens?

**Comment by RANKTW** [comment]
![image](https://user-images.githubusercontent.com/37373560/182657200-21af5a74-0ab0-40e2-bd68-98079b3bf776.png)

**Comment by MRX0077** [comment]
What is make it support regex or what I'm studying this.

**Comment by RANKTW** [comment]
if you want to learn how regex work then will suggest you check out https://regexr.com/

**Comment by MRX0077** [comment]
What is regez for 72 characters token
