### ISSUE TITLE
Token Formatting

### ISSUE THREAD

**Issue by FuckingToasters** [RANKTW/Discord-Token-Checker#46]
First of all, great checker overall however, it would be nice to have support for other token formats like token:pass or mail:pass:token
You could do that, if someone uses wone of these formats, you'll put every thing inside a own variable, then you check the account with the token variable and output it with the fomrat built together again. 

It also would be nice if you can share the API endpoint where you get the flags from (if user is marked as flagged or not)

**Comment by RANKTW** [comment]
about the first part, it currently allows you to input in any format and it will use the original format as output
is that what you mean?

**Comment by FuckingToasters** [comment]
Yes, the first part soltuon helped me with it. What about the second part?
