### ISSUE TITLE
Java 18?

### ISSUE THREAD

**Issue by spxcyz** [RANKTW/Discord-Token-Checker#49]
Not sure what I’ve done wrong I’ve uninstalled and reinstalled Java 8 multiple times but keep getting this error when running start.bat
![71A7A805-36A8-43C6-9041-BA024CB09DFD](https://user-images.githubusercontent.com/115798776/195854304-7942a660-cea1-4db4-b2ef-35ff96682778.png)

**Comment by RANKTW** [comment]
you need uninstall other version first

type `java -version` in command prompt to see which version you using
